name: 'Reusable GPT Review Workflow'

on:
  workflow_call:
    secrets:
      PERSONAL_GITHUB_TOKEN:
        description: 'Derivative token for using the GitHub REST API'
        required: true
      OPENAI_API_KEY:
        description: 'OpenAI API Key'
        required: true
      OPENAI_ORG_KEY:
        description: 'OpenAI Organization ID'
        required: true
      AZURE_OPENAI_API:
        description: 'URL of custom Azure Open AI API'
        required: true
      AZURE_OPENAI_API_KEY:
        description: 'Key of custom Azure Open AI API'
        required: true
      TRANSLATION_API_KEY:
        description: 'Key of translation API'
        required: false
    inputs:
      PATCH_PR:
        description: 'Pull Request Number'
        required: true
        type: string
      PATCH_REPO:
        description: 'GitHub Repository'
        required: true
        type: string
      CACHE_KEY:
        description: 'A unique key for caching dependencies'
        required: false
        type: string

jobs:
  gpt_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ env.CACHE_KEY }}  # キャッシュキーをenvから取得します
          restore-keys: |
            ${{ env.CACHE_KEY }}
        env:
          CACHE_KEY: ${{ inputs.CACHE_KEY || 'CACHE_KEY' }}

      - name: Install gpt-review
        shell: bash
        run: |
          sudo apt-get update
          python3 -m venv .env
          source .env/bin/activate
          python -m pip install --upgrade pip
          python -m pip install langchain==0.0.301
          python -m pip install pydantic==1.10.13
          python -m pip install gpt-review==v0.9.5

      - name: Review PR and make comment
        shell: bash
        run: |
          source .env/bin/activate

          # レビュー
          file_path="./diff.txt"
          # curl -H "Accept: application/vnd.github.v3.diff" \
            # -H "Authorization: Bearer ${{ secrets.PERSONAL_GITHUB_TOKEN }}" \
            # "https://api.github.com/repos/${{ inputs.PATCH_REPO }}/pulls/${{ inputs.PATCH_PR }}" --connect-timeout 10 \
            # > "$file_path"
          # review=$(gpt review diff --diff $file_path | jq -r '.response')
          review="This is Test"

          # 翻訳
          # result=$(curl -X POST 'https://api.deepl.com/v2/translate' \
            # --header 'Authorization: DeepL-Auth-Key ${{ secrets.TRANSLATION_API_KEY }}' \
            # --data-urlencode 'text=$review' \
            # --data-urlencode 'source_lang=EN' \
            # --data-urlencode 'target_lang=JA')

          # コメント
          response=$( \
            curl -s -X POST -H "Authorization: token ${{ secrets.PERSONAL_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ inputs.PATCH_REPO }}/pulls/${{ inputs.PATCH_PR }}/reviews \
            -d "{ \"commit_id\":\"${{ github.event.pull_request.head.sha }}\", \"event\":\"COMMENT\", \"body\":\"$review\"  }")
          echo "$response"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG_KEY: ${{ secrets.OPENAI_ORG_KEY }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY || '' }}
          AZURE_OPENAI_API: ${{ secrets.AZURE_OPENAI_API || '' }}

          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          ACTION_REF: ${{ github.action_ref || env.BRANCH }}
          GIT_COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          LINK: "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"

          FULL_SUMMARY: true
          FILE_SUMMARY: true
          TEST_SUMMARY: false
          BUG_SUMMARY: false
          RISK_SUMMARY: false
          RISK_BREAKING: false
