name: 'Reusable GPT Review Workflow'

on:
  workflow_call:
    secrets:
      PERSONAL_GITHUB_TOKEN:
        description: 'Derivative token for using the GitHub REST API'
        required: true
      OPENAI_API_KEY:
        description: 'OpenAI API Key'
        required: true
      OPENAI_ORG_KEY:
        description: 'OpenAI Organization ID'
        required: true
      AZURE_OPENAI_API:
        description: 'URL of custom Azure Open AI API'
        required: false
      AZURE_OPENAI_API_KEY:
        description: 'Key of custom Azure Open AI API'
        required: false
    inputs:
      PATCH_PR:
        description: 'Pull Request Number'
        required: true
        type: string
      PATCH_REPO:
        description: 'GitHub Repository'
        required: true
        type: string

jobs:
  gpt_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install gpt-review
        shell: bash
        run: |
          sudo apt-get update
          python3 -m venv .env
          source .env/bin/activate
          python -m pip install --upgrade pip
          python -m pip install gpt-review==v0.9.4

      - name: Review PR and make comment
        shell: bash
        run: |
          source .env/bin/activate

          gpt github review \
            --access-token ${{ secrets.PERSONAL_GITHUB_TOKEN }} \
            --pull-request ${{ inputs.PATCH_PR }} \
            --repository ${{ inputs.PATCH_REPO }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG_KEY: ${{ secrets.OPENAI_ORG_KEY }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY || '' }}
          AZURE_OPENAI_API: ${{ secrets.AZURE_OPENAI_API || '' }}
